---
- name: This playbook is to install package
  hosts: all
  become: yes

  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: starting httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: copy index.html file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html/
      mode: 0666

